language: go

sudo: false

go:
  - 1.8

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  - go get github.com/prataprc/monster
  - go install github.com/prataprc/monster ./...

script:
  - go get ./...
  - make test
  - go test -run=xxx -test.bench=. -test.benchmem=true ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci
  - for f in `find ~/ -name "*.prod"`; do echo $f; $HOME/gopath/bin/monster -bagdir ../bags -count 1 -seed 1 $f; done
